---
title: "Series temporales"
author: "Nava Calleros Arath"
date: "2025-04-27"
output: html_document
---




```{python}

#| code-fold: true

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import statsmodels.api as sm
import calendar
from pandas.plotting import register_matplotlib_converters
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.ar_model import AutoReg

```





```{python}
import os

PROJECT_PATH = os.path.expanduser("/Users/arathnava/Desktop/Tareas AN /inegi_data_Arath.xlsx")

inegi_data = pd.read_excel(os.path.join(PROJECT_PATH, "/Users/arathnava/Desktop/Tareas AN /inegi_data_Arath.xlsx"))
```




```{python}
# Cargar datos
#Instale: pip install openpyxl

inegi_data = pd.read_excel("/Users/arathnava/Desktop/Tareas AN /inegi_data_Arath.xlsx", parse_dates=['Periodo'])

#Filtro los datos (2016)
inegi_data = inegi_data[inegi_data["Periodo"].dt.year >= 2016]

```



Crear series temporales 


```{python}
inegi_data.set_index('Periodo', inplace=True)

# Extraer la serie temporal del IPC_BMV
IPC_BMV_ts = inegi_data['IPC_BMV'].dropna()

# Información de la serie temporal
print("Información de la serie temporal del IPC_BMV:")
print(IPC_BMV_ts.info())
print("\nEstadísticas descriptivas:")
print(IPC_BMV_ts.describe())

# Gráfico estático con Matplotlib
plt.figure(figsize=(12, 6))
plt.plot(IPC_BMV_ts.index, IPC_BMV_ts.values, marker='s', linestyle='-', color='royalblue', linewidth=2, markersize=6)
plt.title("Evolución del IPC de la Bolsa Mexicana de Valores", fontsize=18, fontweight='bold')
plt.xlabel("Periodo", fontsize=14)
plt.ylabel("Nivel del IPC", fontsize=14)
plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.6)
plt.tight_layout()
plt.show()

# Gráfico interactivo con Plotly
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=IPC_BMV_ts.index,
    y=IPC_BMV_ts.values,
    mode='lines+markers',
    name='IPC_BMV',
    marker=dict(symbol='diamond', size=8, color='darkred'),
    line=dict(color='navy', width=3)
))

fig.update_layout(
    title="Evolución Histórica del IPC BMV - Análisis Interactivo",
    xaxis_title="Periodo",
    yaxis_title="Nivel del Índice",
    xaxis=dict(rangeslider=dict(visible=True), tickangle=40),
    plot_bgcolor='ghostwhite',
    paper_bgcolor='lightsteelblue',
    font=dict(size=12)
)

fig.show()
```




Comparación 

```{python}
plt.figure(figsize=(14, 7))

sns.lineplot(
    data=df,
    x='Mes',
    y='IPC_BMV',
    hue='Año',
    palette='Set1',      
    marker='D',          
    linewidth=2,
    markersize=8,
    style='Año'          
)

plt.xticks(ticks=range(1, 13), labels=calendar.month_abbr[1:13], fontsize=12)
plt.xlabel('Mes', fontsize=14, fontweight='bold')
plt.ylabel('IPC BMV', fontsize=14, fontweight='bold')
plt.title('Comparación Anual del IPC BMV', fontsize=18, fontweight='bold')
plt.legend(title='Año', title_fontsize=13, fontsize=11, loc='upper left', frameon=True, shadow=True)
plt.grid(True, linestyle='-.', linewidth=0.7, alpha=0.6)
sns.despine(trim=True)  # Quitar bordes superior y derecho para estilo limpio
plt.tight_layout()
plt.show()
```



Comparaciones mensuales


```{python}
plt.figure(figsize=(14, 7))

sns.lineplot(
    data=df,
    x='Año',
    y='IPC_BMV',
    hue='Mes',
    palette='tab20',      
    marker='X',          
    linewidth=2,
    markersize=7,
    style='Mes'           
)

months_sorted = sorted(df['Mes'].unique())
labels = [calendar.month_abbr[m] for m in months_sorted]

plt.xlabel('Año', fontsize=14, fontweight='bold')
plt.ylabel('IPC BMV', fontsize=14, fontweight='bold')
plt.title('Comparación Mensual: Evolución de cada Mes del IPC BMV a lo Largo de los Años', fontsize=18, fontweight='bold')

plt.legend(title='Mes', labels=labels, title_fontsize=13, fontsize=11, loc='upper left', frameon=True, shadow=True)

plt.grid(True, linestyle='--', linewidth=0.7, alpha=0.6)
sns.despine(trim=True)
plt.tight_layout()
plt.show()
```


Otra manera de presentar  DISTRIBUCIÓN. TRIMESTRAL

```{python}
df = pd.read_excel('/Users/arathnava/Desktop/Tareas AN /inegi_data_Arath.xlsx')

df['Periodo'] = pd.to_datetime(df['Periodo'])

df['Año'] = df['Periodo'].dt.year
df['Trimestre'] = df['Periodo'].dt.quarter
df['Año_Trimestre'] = df['Año'].astype(str) + '-Q' + df['Trimestre'].astype(str)

df_filtrado = df[(df['Año'] >= 2016) & (df['Año'] <= 2025)]

plt.figure(figsize=(14, 7))
sns.set(style="whitegrid")

sns.boxplot(
    data=df_filtrado,
    x='Año_Trimestre',
    y='IPC_BMV',   
    hue='Año',
    palette='viridis',
    linewidth=1.2,
    fliersize=5
)

plt.xlabel('Trimestre (Año-Q)', fontsize=14, fontweight='bold')
plt.ylabel('IPC BMV', fontsize=14, fontweight='bold')  # Cambiado aquí
plt.title('Distribución Trimestral del IPC BMV por Año', fontsize=16, fontweight='bold')  # Cambiado aquí
plt.legend(title='Año', bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=12, title_fontsize=13)
plt.xticks(rotation=45, ha='right', fontsize=11)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()
```


ANUAL 

```{python}
sns.set_theme(style="darkgrid")
custom_palette = sns.color_palette("coolwarm", n_colors=len(df['Año'].unique()))

plt.figure(figsize=(12, 7))

sns.boxplot(
    data=df,
    x='Año_Trimestre',
    y='IPC_BMV',           # Cambiado aquí
    hue='Año',
    palette=custom_palette,
    linewidth=2,
    fliersize=6,
    notch=True,
    saturation=0.8
)

plt.xlabel('Trimestre', fontsize=15, fontweight='semibold')
plt.ylabel('IPC BMV', fontsize=15, fontweight='semibold')  # Cambiado aquí
plt.title('Distribución Trimestral del IPC BMV por Año', fontsize=20, fontweight='bold')  # Cambiado aquí

plt.legend(
    title='Año',
    bbox_to_anchor=(1.05, 1),
    loc='upper left',
    frameon=True,
    shadow=True,
    fontsize=12,
    title_fontsize=14
)

plt.xticks(rotation=50, fontsize=12, ha='right')
plt.grid(axis='y', linestyle=':', linewidth=0.7, alpha=0.7)
plt.tight_layout()
plt.show()
```

## Heatmap

```{python}
df_clean = df.dropna(subset=['Mes', 'Año', 'IPC_BMV']).copy()
df_clean['Mes'] = df_clean['Mes'].astype(int)

heatmap_df = df_clean.pivot(index='Mes', columns='Año', values='IPC_BMV')

heatmap_df = heatmap_df.reindex(index=range(1,13))

plt.figure(figsize=(14, 7))

sns.heatmap(
    heatmap_df,
    cmap='Spectral',
    linewidths=0.5,
    linecolor='gray',
    annot=True,
    fmt=".2f",
    cbar_kws={'label': 'IPC BMV'},
    square=False,
    annot_kws={"size": 9}
)

plt.title('Heatmap Mensual del IPC BMV', fontsize=18, fontweight='bold')
plt.xlabel('Año', fontsize=14, fontweight='semibold')
plt.ylabel('Mes', fontsize=14, fontweight='semibold')

plt.yticks(
    ticks=np.arange(0.5, 12.5, 1),
    labels=[calendar.month_abbr[m] for m in range(1, 13)],
    rotation=0,
    fontsize=12
)

plt.xticks(fontsize=12)
plt.tight_layout()
plt.show()
```

  Surface 
  
  
```{python}
Z = heatmap_df.values
x = heatmap_df.columns.astype(str)
y = np.arange(1, 13)

fig = go.Figure(data=[go.Surface(z=Z, x=x, y=y, colorscale='Spectral')])
fig.update_layout(
    title='Superficie del IPC BMV',
    scene=dict(
        xaxis_title='Año',
        yaxis_title='Mes',
        zaxis_title='IPC BMV',
        yaxis=dict(
            tickmode='array',
            tickvals=y,
            ticktext=[calendar.month_abbr[m] for m in y]
        )
    ),
    autosize=True,
    height=600
)

fig.show()
```

OTROS 

```{python}
Z = heatmap_df.values

x = heatmap_df.columns.astype(str)

y = np.arange(1, 13)

fig = go.Figure(
    data=go.Surface(
        z=Z,
        x=x,
        y=y,
        colorscale='Cividis',   
        cmin=np.nanmin(Z),
        cmax=np.nanmax(Z),
        opacity=0.85,
        contours={
            "z": {
                "show": True,
                "start": np.nanmin(Z),
                "end": np.nanmax(Z),
                "size": (np.nanmax(Z) - np.nanmin(Z)) / 15,
                "color": "black",
                "width": 2
            }
        },
        lighting=dict(ambient=0.6, diffuse=0.8, specular=0.3, roughness=0.6),
        lightposition=dict(x=100, y=200, z=0)
    )
)

fig.update_layout(
    title='Superficie 3D del IPC BMV (Estilo Modificado)',
    scene=dict(
        xaxis=dict(
            title='Año',
            tickmode='array',
            tickvals=x,
            ticktext=x,
            backgroundcolor='rgb(230, 230, 230)',
            gridcolor='white',
            zerolinecolor='white'
        ),
        yaxis=dict(
            title='Mes',
            tickmode='array',
            tickvals=y,
            ticktext=[calendar.month_abbr[m] for m in y],
            backgroundcolor='rgb(230, 230, 230)',
            gridcolor='white',
            zerolinecolor='white'
        ),
        zaxis=dict(
            title='IPC BMV',
            backgroundcolor='rgb(230, 230, 230)',
            gridcolor='white',
            zerolinecolor='white'
        ),
        camera=dict(
            eye=dict(x=1.5, y=1.5, z=1.2)  
        )
    ),
    margin=dict(l=60, r=60, b=60, t=90),
    paper_bgcolor='white'
)

fig.show()
```



# Estadísticas de una serie temporal

## Media muestral

La media muestral es el promedio de los valores de la serie temporal a lo largo del tiempo. Se calcula como:

\begin{equation}
\bar{y}=\frac{1}{T} \sum_{t=1}^T y_t
\end{equation}

Donde $T$ es el número total de observaciones de la serie y $y_t$ es el valor de la serie en el tiempo $t$.


```{python}
mean = IPC_BMV_ts.mean()
print(mean)
```


## Varianza muestral 

La varianza muestral cuantifica la dispersión de los valores de la serie alrededor de su media. Se calcula como:


\begin{equation}
s^2=\frac{1}{T-1} \sum_{t=1}^T (y_t-\bar{y})^2
\end{equation}

```{python}
var =  IPC_BMV_ts.mean()
print(var)
```


## Autocovarianza muestral

Cuantifica la covarianza entre dos valores de la serie separados por un retraso (lag) $k$. Se calcula como:

\begin{equation}
\gamma_k=\frac{1}{T} \sum_{t=k+1}^T (y_t-\bar{y})(y_{t-k}-\bar{y})
\end{equation}

En este caso $y_{t-k}$ es el valor de la serie en el tiempo $t-k$.


## Autocorrelación muestral {.tabset}

Es una versión normalizada de la autocovarianza, que mide la correlacion entre dos valores de la serie separados por un retraso $k$, se calcula como:

\begin{equation}
\rho_k=\frac{\gamma_k}{\gamma_0}
\end{equation}

Autocorrelación

```{python}
plt.style.use('seaborn-darkgrid')

plt.figure(figsize=(12, 7))
plot_acf(IPC_BMV_ts, lags=25, alpha=0.05, zero=False)  # IPC_BMV_ts es tu serie temporal

plt.title('Función de Autocorrelación (ACF) del IPC BMV', fontsize=18, fontweight='bold')
plt.xlabel('Rezago (Lag)', fontsize=14)
plt.ylabel('Autocorrelación', fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()
```




LAGGS

```{python}
lags = 14
plt.figure(figsize=(14, 7))

# Colores usando una paleta para diferenciar bien cada lag
colors = plt.cm.viridis_r(np.linspace(0, 1, lags))

for i in range(1, lags + 1):
    plt.plot(
        IPC_BMV_ts.index,
        IPC_BMV_ts.shift(i),
        label=f'Rezago {i}',
        color=colors[i-1],
        linewidth=1.8,
        alpha=0.75
    )

plt.title('Serie Temporal y sus Rezagos (Lags) del IPC BMV', fontsize=18, fontweight='bold')
plt.xlabel('Fecha', fontsize=14)
plt.ylabel('IPC BMV', fontsize=14)
plt.legend(title='Rezagos', fontsize=11, title_fontsize=13, loc='upper right', frameon=True, shadow=True)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()
```


Estacionariedad


```{python}
adf_result = adfuller(IPC_BMV_ts)
print(adf_result)
```

### Una estructura más entendible de la prueba (ADF)
```{python}
print("Resultados del Test de Dickey-Fuller Aumentado (ADF)")
print(f"Serie analizada: IPC_BMV_ts")
print(f"Estadístico de prueba ADF: {adf_result[0]:.4f}")
print(f"Orden de rezago seleccionado: {adf_result[2]}")
print(f"Valor p: {adf_result[1]:.4f}")

if adf_result[1] < 0.05:
    print("Conclusión: Rechazamos la hipótesis nula. La serie es estacionaria.")
else:
    print("Conclusión: No se rechaza la hipótesis nula. La serie no es estacionaria.")

print("Hipótesis alternativa: La serie es estacionaria")
```
la serie es estacionaria 


Diferenciación

```{python}
IPC_BMV_diff = IPC_BMV_ts.diff().dropna()

plt.figure(figsize=(12, 6))
plt.plot(
    IPC_BMV_diff.index,
    IPC_BMV_diff.values,
    marker='d',
    linestyle='-',
    color='teal',
    alpha=0.8,
    linewidth=2,
    markersize=6
)
plt.title("Serie Temporal Diferenciada del IPC BMV", fontsize=18, fontweight='bold')
plt.xlabel("Periodo", fontsize=14)
plt.ylabel("Diferencia del IPC BMV", fontsize=14)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()
```


# Descomposición  {.tabset}

Una serie temporal $y_t$ puede descomponerse en la suma (aditiva) de sus componentes principales:


\begin{equation}
y_t = T_t+S_t+R_t
\end{equation}

Donde $T_t$ es la tendencia (movimiento a largo plazo), $S_t$ es la estacionalidad (patrones repetitivos en intervalos regulares) y $R_t$ es el residuo (ruido aleatorio). O bien, de manera multiplicativa:

\begin{equation}
y_t = T_t S_t R_t
\end{equation}


DESCOMPOSICIÓN

```{python}
decomposition = seasonal_decompose(IPC_BMV_ts, model='additive', period=12)

fig, axes = plt.subplots(4, 1, figsize=(14, 10), sharex=True)

axes[0].plot(IPC_BMV_ts, color='#1f77b4')
axes[0].set_title('Serie Temporal Original IPC BMV', fontsize=16, fontweight='bold')
axes[0].grid(alpha=0.3)


axes[1].plot(decomposition.trend, color='#ff7f0e')
axes[1].set_title('Componente de Tendencia', fontsize=16, fontweight='bold')
axes[1].grid(alpha=0.3)

axes[2].plot(decomposition.seasonal, color='#2ca02c')
axes[2].set_title('Componente Estacional', fontsize=16, fontweight='bold')
axes[2].grid(alpha=0.3)

axes[3].plot(decomposition.resid, color='#d62728')
axes[3].set_title('Componente Residual', fontsize=16, fontweight='bold')
axes[3].grid(alpha=0.3)

plt.xlabel('Fecha', fontsize=14)
plt.tight_layout()
plt.show()
```


Serie diferenciada

```{python}
IPC_BMV_diff = IPC_BMV_ts.diff().dropna()

decomposition_diff = seasonal_decompose(IPC_BMV_diff, model='additive', period=12)

fig, axes = plt.subplots(4, 1, figsize=(14, 10), sharex=True)
axes[0].plot(IPC_BMV_diff, color='#007ACC')
axes[0].set_title('Serie Temporal Diferenciada IPC BMV', fontsize=16, fontweight='bold')
axes[0].grid(alpha=0.3)


axes[1].plot(decomposition_diff.trend, color='#FF8C00')
axes[1].set_title('Componente de Tendencia', fontsize=16, fontweight='bold')
axes[1].grid(alpha=0.3)


axes[2].plot(decomposition_diff.seasonal, color='#2E8B57')
axes[2].set_title('Componente Estacional', fontsize=16, fontweight='bold')
axes[2].grid(alpha=0.3)

axes[3].plot(decomposition_diff.resid, color='#B22222')
axes[3].set_title('Componente Residual', fontsize=16, fontweight='bold')
axes[3].grid(alpha=0.3)

plt.xlabel('Fecha', fontsize=14)
plt.tight_layout()
plt.show()
```



AutoRegresión {.tabset}



Coeficientes

```{python}
IPC_BMV_ar = AutoReg(IPC_BMV_ts, lags=10).fit()

print(IPC_BMV_ar.params)
```


Gráfica

```{python}
IPC_BMV_ar_res = pd.DataFrame({'IPC_BMV_Real': IPC_BMV_ts, 'IPC_BMV_Ajustado': Valores_ajustados})

plt.figure(figsize=(14, 7))

plt.plot(IPC_BMV_ar_res.index, IPC_BMV_ar_res['IPC_BMV_Real'], label='IPC BMV Real', color='darkgreen', linewidth=2)
plt.plot(IPC_BMV_ar_res.index, IPC_BMV_ar_res['IPC_BMV_Ajustado'], label='IPC BMV Ajustado', color='darkorange', linewidth=2, linestyle='-.')

plt.title('Valores Reales vs Ajustados del IPC BMV', fontsize=18, fontweight='bold')
plt.xlabel('Fecha', fontsize=14)
plt.ylabel('IPC BMV', fontsize=14)
plt.legend(title='Serie', fontsize=12, title_fontsize=13, loc='upper left', frameon=True, shadow=True)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()
```


Residuos

```{python}
residuos = IPC_BMV_ar.resid

plt.figure(figsize=(14, 6))
plt.plot(residuos.index, residuos, color='mediumvioletred', linewidth=1.8, alpha=0.85, label='Residuos')
plt.axhline(0, color='gray', linestyle='--', linewidth=1)
plt.title('Residuos del Modelo AR - IPC BMV', fontsize=18, fontweight='bold')
plt.xlabel('Fecha', fontsize=14)
plt.ylabel('Residuos', fontsize=14)
plt.legend(fontsize=12)
plt.grid(True, linestyle=':', alpha=0.6)
plt.tight_layout()
plt.show()
```


Forecast

```{python}
forecast_steps = 12

forecast_values = IPC_BMV_ar.predict(start=len(IPC_BMV_ts), end=len(IPC_BMV_ts) + forecast_steps - 1)


forecast_index = pd.date_range(start=IPC_BMV_ts.index[-1] + pd.offsets.MonthBegin(1), periods=forecast_steps, freq='M')

plt.figure(figsize=(14, 7))

# Serie original
plt.plot(IPC_BMV_ts.index, IPC_BMV_ts, label='Serie Original', color='darkblue', linewidth=2)

plt.plot(forecast_index, forecast_values, label='Pronóstico', color='darkorange', linestyle='--', linewidth=2)

plt.title('Pronóstico del IPC BMV', fontsize=18, fontweight='bold')
plt.xlabel('Fecha', fontsize=14)
plt.ylabel('IPC BMV', fontsize=14)
plt.legend(loc='upper left', fontsize=12, title='Serie', title_fontsize=13, frameon=True, shadow=True)
plt.grid(True, linestyle=':', alpha=0.7)
plt.tight_layout()
plt.show()
```






